CREATE TABLE IF NOT EXISTS "chat-genius_account" (
	"user_id" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"provider_account_id" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "chat-genius_account_provider_provider_account_id_pk" PRIMARY KEY("provider","provider_account_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "chat-genius_channel_member" (
	"channel_id" integer NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"is_admin" boolean DEFAULT false NOT NULL,
	"joined_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "chat-genius_channel_member_channel_id_user_id_pk" PRIMARY KEY("channel_id","user_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "chat-genius_channel" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chat-genius_channel_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"description" text,
	"is_private" boolean DEFAULT false NOT NULL,
	"created_by" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "chat-genius_message" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chat-genius_message_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"content" text NOT NULL,
	"channel_id" integer NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "chat-genius_session" (
	"session_token" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "chat-genius_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"email_verified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "chat-genius_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "chat-genius_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "chat-genius_account" ADD CONSTRAINT "chat-genius_account_user_id_chat-genius_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."chat-genius_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "chat-genius_channel_member" ADD CONSTRAINT "chat-genius_channel_member_channel_id_chat-genius_channel_id_fk" FOREIGN KEY ("channel_id") REFERENCES "public"."chat-genius_channel"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "chat-genius_channel_member" ADD CONSTRAINT "chat-genius_channel_member_user_id_chat-genius_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."chat-genius_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "chat-genius_channel" ADD CONSTRAINT "chat-genius_channel_created_by_chat-genius_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."chat-genius_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "chat-genius_message" ADD CONSTRAINT "chat-genius_message_channel_id_chat-genius_channel_id_fk" FOREIGN KEY ("channel_id") REFERENCES "public"."chat-genius_channel"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "chat-genius_message" ADD CONSTRAINT "chat-genius_message_user_id_chat-genius_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."chat-genius_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "chat-genius_session" ADD CONSTRAINT "chat-genius_session_user_id_chat-genius_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."chat-genius_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "account_user_id_idx" ON "chat-genius_account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "channel_member_channel_id_idx" ON "chat-genius_channel_member" USING btree ("channel_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "channel_member_user_id_idx" ON "chat-genius_channel_member" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "channel_created_by_idx" ON "chat-genius_channel" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "channel_name_idx" ON "chat-genius_channel" USING btree ("name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "message_channel_id_idx" ON "chat-genius_message" USING btree ("channel_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "message_user_id_idx" ON "chat-genius_message" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "session_user_id_idx" ON "chat-genius_session" USING btree ("user_id");